name: simplethread
description: "Simple Thread is a chatting application for different User"
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.1.0+1
environment:
  sdk: ">=3.2.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  lottie: ^2.7.0
  page_transition: ^2.1.0
  firebase_core: ^2.24.2
  google_fonts: ^6.1.0
  firebase_auth: ^4.16.0
  hidden_drawer_menu: ^3.0.1
  cloud_firestore: ^4.14.0
  flutter_svg: ^2.0.9
  connectivity_plus: ^5.0.2
  provider: ^6.1.1
  url_launcher: ^6.2.4
  shared_preferences: ^2.2.2
  visibility_detector: ^0.4.0+2
  font_awesome_flutter: ^10.7.0
  path_provider: ^2.1.2
  google_nav_bar: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animation/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
