// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsAxLt26_KHWsgzS6c5bXmSu_3SPSuaPQ',
    appId: '1:1047577824208:web:34f9fa9377aacc523447d5',
    messagingSenderId: '1047577824208',
    projectId: 'chatapp-68acd',
    authDomain: 'chatapp-68acd.firebaseapp.com',
    storageBucket: 'chatapp-68acd.appspot.com',
    measurementId: 'G-KR4TCBRH8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5mP963vlx6OM8Avke6dw1UOBs3O7qfSQ',
    appId: '1:1047577824208:android:f753b07b45479f3b3447d5',
    messagingSenderId: '1047577824208',
    projectId: 'chatapp-68acd',
    storageBucket: 'chatapp-68acd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMnvqih75ghBNUuPl_AJQkVlMGdqDvJs0',
    appId: '1:1047577824208:ios:36d94e9f29959c073447d5',
    messagingSenderId: '1047577824208',
    projectId: 'chatapp-68acd',
    storageBucket: 'chatapp-68acd.appspot.com',
    iosBundleId: 'com.example.simplethread',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMnvqih75ghBNUuPl_AJQkVlMGdqDvJs0',
    appId: '1:1047577824208:ios:861d396ba2acaa203447d5',
    messagingSenderId: '1047577824208',
    projectId: 'chatapp-68acd',
    storageBucket: 'chatapp-68acd.appspot.com',
    iosBundleId: 'com.example.simplethread.RunnerTests',
  );
}
